title: Shuzhan Yang
desciption: >
  I'm currently a graduate student looking for Phd. I love computer graphics and especially rendering. In the past, I worked as a 3d designer for product in a sales department. I graduated from Wuhan University with a bachelor's degree and am currently studying at Sichuan Normal University. I am currently conducting research on MCMC, and my supervisor Han Su is involved in AI related research.
email: 1534596814@qq.com
baseurl: "/atlas-jekyll-theme" # the subpath of your site, e.g. /blog
#replace nrdybhu1.github.io with your domainname.com
url: "https://nrdybhu1.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  yangshuzhan
markdown: kramdown
page_excerpts: true
favicon: "/img/atlas.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
