title: Shuzhan Yang
description: My interests are rendering and machine learning.
email: yangshuzhan1996@qq.com
baseurl: "/profile" # the subpath of your site, e.g. /blog
#replace nrdybhu1.github.io with your domainname.com
url: "https://yangshuzhan.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  yangshuzhan
markdown: kramdown
page_excerpts: true
favicon: "/img/atlas.png"
collections:
  posts:
    permalink: "/blog/:title:output_ext"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
- scope:
    path: ''
  values:
    image: "/img/preview.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-redirect-from
- jemoji
- jekyll-paginate

paginate: 5
paginate_path: "/blog/page-:num/"
